version: '3'
services:
  strapi:
    image: opsciprojet-strapi
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: safepassword
    networks:
      - bridge-network

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: safepassword
      POSTGRES_DB: strapi
    networks:
      - bridge-network

  react:
    build: ./opsci-strapi-frontend
    ports:
      - '5173:5173'
    depends_on:
      - strapi
    environment:
      REACT_APP_API_URL: http://localhost:1337
      REACT_APP_API_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
    networks:
      - bridge-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    expose:
      - '2181'
    networks:
      - bridge-network

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    env_file: .env
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://${BROKER_URL}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: '1'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_DIRS: /kafka/logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - bridge-network

  product-producer:
    image: arthurescriou/product-producer:1.0.0
    container_name: product-producer
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      STRAPI_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
      STRAPI_URL: http://strapi:1337
      TOPIC: product
      ERROR_TOPIC: errors
      FILE_NAME: /products
    volumes:
      - /home/jsvgjsvjsjf/Documents/opsci/opsciprojet/products_data/products.csv:/products
    networks:
      - bridge-network

  product-consumer:
    image: arthurescriou/product-consumer:1.0.3
    container_name: product-consumer
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      STRAPI_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
      STRAPI_URL: http://strapi:1337
      TOPIC: product
      BEGINNING: false
      ERROR_TOPIC: errors
    networks:
      - bridge-network

  event-producer:
    image: arthurescriou/event-producer:1.0.3
    container_name: event-producer
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      STRAPI_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
      STRAPI_URL: http://strapi:1337
      TOPIC: event
      BEGINNING: false
      ERROR_TOPIC: errors
      FILE_NAME: /events
    volumes:
      - /home/jsvgjsvjsjf/Documents/opsci/opsciprojet/events_data/events.csv:/events
    networks:
      - bridge-network

  event-consumer:
    image: arthurescriou/event-consumer:1.0.0
    container_name: event-consumer
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      STRAPI_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
      STRAPI_URL: http://strapi:1337
      TOPIC: event
      BEGINNING: false
      ERROR_TOPIC: errors
    networks:
      - bridge-network

  stock-producer:
    image: arthurescriou/stock-producer:1.0.0
    container_name: stock-producer
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      STRAPI_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
      STRAPI_URL: http://strapi:1337
      TOPIC: stock
      FILE_NAME: /stocks
    volumes:
      - /home/jsvgjsvjsjf/Documents/opsci/opsciprojet/stocks_data/stocks.csv:/stocks
    networks:
      - bridge-network

  stock-consumer:
    image: arthurescriou/stock-consumer:1.0.0
    container_name: stock-consumer
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      STRAPI_TOKEN: cd73090d55cae7efefcc726ab26b76cc36f565fc013ef7d2cdd783e85c95fbf065d8c2bf1303f7c399f23cb45e5ac4409bbb016547ed111c5102f29c73dc01f8c36609056d8ff8498012c57cbb3eb095474abde8e98b9867c6c268aeb6b4598b48d84ef2054e0a3e8920b672809ca2efc2ee5fac626d7c78e732b5242bae7ace
      STRAPI_URL: http://strapi:1337
      TOPIC: stock
      BEGINNING: false
      ERROR_TOPIC: errors
    networks:
      - bridge-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - /home/jsvgjsvjsjf/Documents/opsci/opsciprojet_suite/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    environment:
      - TZ=Europe/Paris
    networks:
      - bridge-network

  mqtt-kafka-connector:
    image: arthurescriou/mqtt-kafka-connector:1.0.0
    container_name: mqtt-kafka-connector
    environment:
      BROKER_1: ${BROKER_URL}
      BROKER_2: ${BROKER_URL}
      BROKER_3: ${BROKER_URL}
      KAFKA_TOPIC: 'stock'
      MQTT_TOPIC: 'topic'
      MQTT_ENDPOINT: 'ws://mosquitto:1883'
    depends_on:
      - kafka
      - mosquitto
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

